Dev
Blackdeer1524/Dict2FlashcardsQT pull request #3
Opened 2023-05-14 19:19 UTC by Qesait

Пока ещё ничего не сделано, просто заготовки

2023-05-14 19:59 UTC, Blackdeer1524 commented
сделай не lib/client, а client/lib

2023-05-15 10:35 UTC, Blackdeer1524 requested changes

2023-05-15 10:35 UTC, Blackdeer1524 commented on client/lib/connection/include/ServerConnection.h
> +using boost::asio::ip::tcp;
В инклюде не рекомендовано использовать `using`

2023-05-15 10:35 UTC, Blackdeer1524 commented on client/lib/plugin_wrappers/tests/src/AudioPluginWrapper_tests.cpp
> +#include "../../include/wrappers/AudioPluginWrapper.h"
Почему не создать либу под каждый врапер и линкануть её к тесту?

2023-05-16 14:56 UTC, Blackdeer1524 commented
lgtm

2023-05-16 15:29 UTC, merged

2023-06-12 08:16 UTC, a-badin reviewed
Оцениваю на 18

2023-06-12 08:16 UTC, a-badin commented on client/lib/connection/src/ServerConnection.cpp
> +    socket_.close();
Сокет сам умеет вызывать close в деструкторе